# name: Notification on push

# on:
#   push:
#     branches:
#     - main

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:   
#     - name: Discord notification
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        uses: Ilshidur/action-discord@master
#        with:
#          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
         
name: Notification on push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: GitHub Actions
        DISCORD_AVATAR: https://cdn-icons-png.flaticon.com/512/25/25231.png
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new commit has been pushed to {{ EVENT_PAYLOAD.repository.full_name }}'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
